name: Deploy Angular 20 to GitHub Pages

on:
  push:
    branches:
      - main    # O la rama que uses como principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # para que peaceiris/actions-gh-pages use su propio token

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'       # Angular 20 funciona bien con Node 18+

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href "https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY_NAME/"
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/my-profile   # carpeta generada tras el build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
